### ISSUE TITLE
Taze goshgylar

### ISSUE THREAD

**Issue by PermanAtayev** [gnurgeldiyev/serpay#2]
Salam, taze goshgylaram goshup bilersing mening pikirimche internetten scrape edip.

**Comment by gnurgeldiyev** [comment]
Salam Perman. Elbetde, approve edilmeli hem gaty kop goşgy dur şuwagt DB de. Yakynda wagt ayyrmakcy yene ;)

**Comment by PermanAtayev** [comment]
Komek gerek bolsa ayt, menem komek ederin

**Comment by gnurgeldiyev** [comment]
Elbetde gowy bolar, men su proyekt tab'ni acaryn her bir task ucin
